// ignore_for_file: depend_on_referenced_packages

import 'dart:convert';
import 'dart:io';

import 'package:darwin_sdk_kit/darwin_sdk_kit.dart';
import 'package:path/path.dart' as p;
import 'package:xcross/src/flutter/build/info_plist.dart';
import 'package:xcross/src/flutter/build/resources/asset_catalog_compiler.dart';
import 'package:xcross/src/flutter/build/resources/storyboard_compiler.dart';

/// Offline preparation only: never signs, connects to, or installs on a device.
/// Input is Integration.xcassets generated by asset_catalog_audit.dart.
Future<void> main(List<String> arguments) async {
  if (arguments.length != 3) {
    stderr.writeln(
      'Usage: build_asset_lookup_probe.dart <catalog> <new-output-root> <tool-cache>',
    );
    exitCode = 64;
    return;
  }
  final catalog = Directory(arguments[0]).absolute.path;
  final root = Directory(arguments[1]).absolute;
  if (root.existsSync()) {
    throw StateError('Output must be a new directory: ${root.path}');
  }
  await root.create(recursive: true);
  final app = Directory(p.join(root.path, 'AssetLookupProbe.app'));
  await app.create();
  await AssetCatalogCompiler(
    cacheRoot: Directory(arguments[2]).absolute.path,
  ).compile([catalog], app.path);
  final validation = Directory(p.join(app.path, 'Validation'));
  await validation.create();
  for (final name in [
    'Single1',
    'Tiny1',
    'Single2',
    'Single3',
    'Scaled',
    'EqualPixels',
    'AlphaVariants',
  ]) {
    final set = p.join(catalog, '$name.imageset');
    final contents =
        jsonDecode(await File(p.join(set, 'Contents.json')).readAsString())
            as Map;
    for (final raw in contents['images'] as List) {
      final image = raw as Map<String, dynamic>;
      final scale = (image['scale'] as String).replaceAll('x', '');
      await File(
        p.join(set, image['filename'] as String),
      ).copy(p.join(validation.path, '$name-$scale.png'));
    }
  }
  final storyboard = File(
    p.join(
      p.dirname(Platform.script.toFilePath()),
      'asset_lookup_launch.storyboard',
    ),
  );
  final compiled = StoryboardCompiler().compile(
    await storyboard.readAsString(),
    source: storyboard.path,
  );
  for (final entry in compiled.entries) {
    final file = File(p.join(app.path, 'LaunchScreen.storyboardc', entry.key));
    await file.parent.create(recursive: true);
    await file.writeAsBytes(entry.value);
  }
  // XML declaration must be the first bytes in the file.
  // ignore: leading_newlines_in_multiline_strings
  var plist = '''<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
<key>CFBundleIdentifier</key><string>dev.xcross.iosAotProbe</string>
<key>CFBundleDisplayName</key><string>xcross Asset Probe</string>
<key>CFBundleExecutable</key><string>Runner</string>
<key>CFBundleName</key><string>xcross Asset Probe</string>
<key>CFBundlePackageType</key><string>APPL</string>
<key>CFBundleVersion</key><string>30</string>
<key>CFBundleShortVersionString</key><string>1.0.0</string>
<key>MinimumOSVersion</key><string>16.0</string>
<key>UIDeviceFamily</key><array><integer>1</integer><integer>2</integer></array>
<key>UILaunchStoryboardName</key><string>LaunchScreen</string>
<key>UIFileSharingEnabled</key><true/>
<key>UISupportedInterfaceOrientations</key><array><string>UIInterfaceOrientationPortrait</string></array>
</dict></plist>''';
  plist = InfoPlist.mergeAssetMetadata(
    plist,
    await File(p.join(app.path, 'asset-info.plist')).readAsString(),
  );
  await File(p.join(app.path, 'Info.plist')).writeAsString(plist);
  final sdk = DarwinSdk(DarwinSdk.nativeInstallDir());
  final sdkRoot = sdk.iPhoneOSSdk();
  final settings =
      jsonDecode(await File(p.join(sdkRoot, 'SDKSettings.json')).readAsString())
          as Map;
  final sdkVersion = settings['Version'] as String;
  final source = p.join(
    p.dirname(Platform.script.toFilePath()),
    'asset_lookup_probe.m',
  );
  final object = p.join(root.path, 'probe.o');
  final frameworks = p.join(sdkRoot, 'System', 'Library', 'Frameworks');
  final subframeworks = p.join(sdkRoot, 'System', 'Library', 'SubFrameworks');
  final commands = [
    [
      await DarwinSdk.resolveDarwinClang(sdk),
      '-target',
      'arm64-apple-ios16.0',
      '-isysroot',
      sdkRoot,
      '-F',
      subframeworks,
      '-fobjc-arc',
      '-c',
      source,
      '-o',
      object,
    ],
    [
      await DarwinSdk.resolveLd64Lld(sdk),
      '-arch',
      'arm64',
      '-platform_version',
      'ios',
      '16.0',
      sdkVersion,
      '-syslibroot',
      sdkRoot,
      '-o',
      p.join(app.path, 'Runner'),
      object,
      '-F',
      frameworks,
      '-F',
      subframeworks,
      '-framework',
      'UIKit',
      '-framework',
      'Foundation',
      '-framework',
      'CoreGraphics',
      '-lobjc',
      '-lc',
    ],
  ];
  await File(
    p.join(root.path, 'build-commands.json'),
  ).writeAsString(jsonEncode(commands));
  for (final command in commands) {
    final result = await Process.run(command.first, command.skip(1).toList());
    if (result.exitCode != 0) {
      throw StateError('${result.stdout}\n${result.stderr}');
    }
  }
  stdout.writeln('Unsigned device probe ready: ${app.path}');
}
